language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest -v
- python freeze.py
deploy:
  provider: s3
  secret_access_key:
    secure: Vwr6vGyIsyetq6g8Tj6tUMxwanCSigrXKyHut3NZOimf0fnKi6B7WfIV11UCg2CYf1bSMDO3ye46FJwDWdv07YIv9sx4Nkin30l2lsT4Z7c+ZAHzWmxKZ9msoHVmoRv1FcjmFtCVZv6HBphcSX31Sq4Jp9OKYcQiQp41Ni2k5/FstnRCcfuT5jkryWmBkrgvymGAzP748NOixaVtfyyRNDkylxgqGItTX7ELC9bqKQ1BjhKHu0qLnpI/2k0B0qDo3jRepUNUmmn7qXTOh/NoB1ioozGfP9FJCZMzjL9uDaBeZfGUu3UXDyDBxLgO4flnqqJN12BVXTWrd1hSyAoAe/MfPhqxO9OT+0a2WO22u8KLyDogD75BEXUTA72jGa6PyPkHodxX42+wavn4RHYiQ6b+VfEtL6uUarJ70RJPsID2ind7CCbxMQSO1U/pFvxDxpEIRY2lH2aU4eIDW1k7lPfIyuMkK3l0GYLejq57Uv4HiJZe7ETURfdX7IoEYPSbySJDB1WprFlZ2ypxlvAPD2uNXJ1hpBxwd83jnvP1c5ZWXBfv5YI+T5/yndpbe7wge0lC3//xRhv6iQ8eEY72+h3H6wK6jv74tFAFWjIZEojpWgeQkiEP6OgFPL7pe+sNDEQpAA/dvjAv3hnEovDTlOGHvzy6qGgmr4lzgnbpDy0=
  access_key_id:
    secure: RrJuVChRhUo//P9iZg8BAV57g2jzmaPntf6pXfFIL/+e3iE7fq6kop9Aj9MgEkSPohWgQg2+ak8UnKEOmyVvTpyY7jmbd4AbWnkDpD6imkwjiZ58BAZqHnZDHrL8aEN8kA/l4tvCit3ewsIMZfHMWLICOpP8KB6/8ZHUiId1gIKCucfOMQOMcVT2oclmx1OwrkKUHY/W33eDSVEsgfazmsDa26vfNJU8v6uEdR6nJA95H4cAOBV6Uxp8m44yozZayLONCGkUdJvpWkQjx2Q9NCnz144yOJU1GpugEkX0Q48meAcEvo5feE8pUGneY3+i6M9zf0OFvPzf+yp6jxa68pYQFFxqypDpFYRqEtl3jVYPyPrR/SyvRpoDtyJUKkVIPrO/QWD7Qn+l98/fVM+UIn6pcqnN8ckiimm3hFgUYUDuN48zaKcGdNiW0BXQfvuwdjAs+4rWeQTgc7dxojiKnLDcA97SlueVspDFvrkxWMNf8GaTKEHs2p9FKHYFttaBwKcnYIlkYvnDrq8FFpCOf7JY1IRfCFR/QorSdFiZUoK9cKhIpefupoO5pJ6MmUV7R1mrzzraK9DqDys55d9lgH+CsWa4WHTu92iSGt5s/If5oE1/HG1CPeCPUxtHjE/rkdoC4fqJvqWkRTX3nrNQoEHJ9lm1k78pvJO6+4mIMZw=
  bucket: hraew.autophagy.io
  skip_cleanup: true
  region: eu-central-1
  local_dir: hraew/build
notifications:
  email: false
